services:
  - type: web
    name: scrum-poker-app
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
